version: '2'
services:
    reactsample-app:
        image: reactsample
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reactsample-postgresql:5432/ReactSample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reactsample-postgresql:
        extends:
            file: postgresql.yml
            service: reactsample-postgresql
